# docker-compose.yml
version: '3'
services:
 database:
  image: 
   - ./postgre   
  env_file:
   - ./postgre/database.env
  volumes:
  ## - database-data:/var/lib/postgresql/12/main/base
   - database-data:/home/lex/PostgresBase
  ports:
   - 5432:5432
  
volumes:
 database-data:
