version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: alex
      MYSQL_PASSWORD: 12345678
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_USER: alex
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  dbdata: