version: '3.8'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - dbpostgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: 12345678

  drupal:
    image: drupal
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 12345678
    volumes:
      - d1:/var/www/html/
    ports:
      - 9999:80

  joomla:
    image: joomla
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: alex
      JOOMLA_DB_PASSWORD: 12345678
      JOOMLA_DB_NAME: mydb

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mydb
      MYSQL_USER: alex
      MYSQL_PASSWORD: 12345678
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
    volumes:
      - dbmysql:/var/lib/mysql
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_PASSWORD: 12345678
      PMA_USER: alex

volumes:
  dbpostgres:
  dbmysql:
  ng:
  d1: