# docker-compose.yml
version: '3.8'
services:
 database:
  image: "postgres:latest"   
  env_file:
   - database.env
  volumes:
   - database-data:/var/lib/postgresql/db
  ## - database-data:/home/lex/PostgresBase
  ports:
   - 5432:5432

 pgadmin4:
  image: "dpage/pgadmin4"
  env_file:
   - pgadmin4.env
  ports: 
   - 5050:80

volumes:
 database-data:

 